language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
branches:
  only: 
    - master
    - dev
before_install:
  - 'if [ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then npm install -g auto-changelog; fi'
before_script:
  - git config --global user.name "JH Kim"
  - git config --global user.email "couldseeme@icon.foundation"
after_success:
  - 'if [ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then bash ./travis/deploy.sh; fi'